### ISSUE TITLE
add events support

### ISSUE THREAD

**Issue by stardiviner** [osv/web-completion-data#2]
I hope can add events support. Like `onclick` for `<a>`.
What do you think?

**Comment by osv** [comment]
Hello, before adding new things, I'd like to convert ALL data into yaml, smtg like https://github.com/osv/h5doc/blob/master/text/attr-values.yaml 
After that I have plan to add some attributes, update docs, examples. etc.

**Comment by stardiviner** [comment]
Great, thanks

**Comment by osv** [comment]
I keep it open, to remind me this task :)

**Comment by osv** [comment]
Done in v0.2
